<?php
/*********************************\ 
SETTINGS v1.0.17.1&beta;
 do not edit this file ! use admin cp unless told otherwise
\*********************************/
$settings['logo'] = "/images/logo.png";
$settings['domain_size'] = "2.5";
$settings['mail_message_id'] = "1";
$settings['mail_parameters'] = "";
$settings['adminemail'] = "jim@noideersoftware.co.uk";
$settings['server_tz'] = "Europe/London";
$settings['paypal_email'] = "jim.richardson06@btinternet.com";
$settings['avataruploadpath'] = "/uploads/avatars";
$settings['siteclosed'] = "1";
$settings['siteclosed_url'] = "https://noideersoftware.co.uk/ebola.html";
$settings['sitename'] = "Local Site with bits";
$settings['use_address'] = "0";
$settings['address_street'] = "5 Oriel House, 46 Worcester Road";
$settings['address_city'] = "Malvern";
$settings['address_postcode'] = "WR14 4AA";
$settings['address_phone'] = "07707 893449";
$settings['pwdlen'] = "3";
$settings['https'] = "0";
$settings['url'] = "http://localhost/yoursite";
$settings['showphp'] = "0";
$settings['steamkey'] = "91313FE1EEF89AD8E5ED16ADBD51DF93";
$settings['showsidebox'] = "0";
$settings['templatecomments'] = "1";
$settings['forumtabs'] = "1";
$settings['version'] = "1.0.17.1&beta;";
$settings['session'] = "1";
$settings['year'] = "1";
$settings['start_year'] = "2014";
$settings['per_page'] = "5";
$settings['ip_count'] = "2";
$settings['theme_path'] = "light";
$settings['show_device'] = "1";
$settings['time_format'] = "g:i:s a";
$settings['date_format'] = "l, d M Y";
$settings['disable_plugin'] = "0";
?>