<?php
/*********************************\ 
SETTINGS v1.0.17.1&psi;
 do not edit this file ! use admin cp unless told otherwise
\*********************************/
$settings['logo'] = "/images/logo.png";
$settings['mail_message_id'] = "1";
$settings['mail_parameters'] = "";
$settings['adminemail'] = "name@domain.com";
$settings['server_tz'] = "Europe/London";
$settings['paypal_email'] = "name@domain.com";
$settings['avataruploadpath'] = "/uploads/avatars";
$settings['siteclosed'] = "0";
$settings['siteclosed_url'] = "https://google.co.uk";
$settings['sitename'] = "Your Game Control Panel";
$settings['use_address'] = "0";
$settings['address_street'] = "";
$settings['address_city'] = "";
$settings['address_postcode'] = "";
$settings['address_phone'] = "01905 999999";
$settings['pwdlen'] = "3";
$settings['https'] = "1";
$settings['url'] = "http://localhost/LSGM-Web";
$settings['showphp'] = "0";
$settings['steamkey'] = "91313FE1EEF89AD8E5ED16ADBD51DF93";
$settings['showsidebox'] = "0";
$settings['templatecomments'] = "1";
$settings['forumtabs'] = "1";
$settings['version'] = "1.0.0.0&psi;";
$settings['session'] = "1";
$settings['year'] = "0";
$settings['start_year'] = "2014";
$settings['per_page'] = "5";
$settings['ip_count'] = "4";
$settings['theme_path'] = "default";
$settings['show_device'] = "0";
$settings['time_format'] = "h:i:s";
$settings['date_format'] = "d-m-Y";
$settings['panel_url'] = "https://noideersoftware.co.uk:10000";
$settings['domain_size'] = "0.5";
$settings['cookie_url'] = "/misc.php?action=27015";
$settings['disable_plugin'] = "0";
$settings['new_posts'] = "5";
$settings['olark_key'] = "";
$settings['game_server'] = "http://lightsoundstudiosuk.co.uk"; 
?>
