<?php
/*********************************\ 
SETTINGS v1.0.17.1&psi;
 do not edit this file ! use admin cp unless told otherwise
\*********************************/
$settings['logo'] = "/images/logo.png"; // SET THIS : name your image logo.png or change it to your image name : zer0 : ex. /images/yourimage.jpg : zer0
$settings['mail_message_id'] = "1";
$settings['mail_parameters'] = "";
$settings['adminemail'] = "name@domain.com"; // SET THIS : zer0
$settings['server_tz'] = "Europe/London";
$settings['paypal_email'] = "name@domain.com"; // SET THIS : zer0
$settings['avataruploadpath'] = "uploads/avatars"; // DEFAULT : Change this path if you need.  : zer0
$settings['siteclosed'] = "0"; // DEFAULT 0 (False) : I guess if your site is down it is best to redirect to Google? I think a maintenance page would be a better option. : zer0
$settings['siteclosed_url'] = "https://google.com"; //SET THIS : use whatever localized website you like. Include the full url : zer0
$settings['sitename'] = "Your Game Control Panel"; // SET THIS : This is your site title  : zer0
$settings['use_address'] = "0";
$settings['address_street'] = "";
$settings['address_city'] = "";
$settings['address_postcode'] = "";
$settings['address_phone'] = "01905 999999";
$settings['pwdlen'] = "3";
$settings['https'] = "1";
$settings['url'] = "http://localhost/LSGM-Web"; // DEFAULT : Change this to match your domain and directory. : zer0 : ex. https://www.yourdomain.com/ OR https://yourdomain.com/gameservers/ 
$settings['showphp'] = "0"; // Still discovering http://localhost/LSGM-Web
$settings['steamkey'] = "91313FE1EEF89AD8E5ED16ADBD51DF93";
$settings['showsidebox'] = "0";
$settings['templatecomments'] = "1";
$settings['forumtabs'] = "1";
$settings['version'] = "1.0.0.0&psi;";
$settings['session'] = "1";
$settings['year'] = "0";
$settings['start_year'] = "2014";
$settings['per_page'] = "5";
$settings['ip_count'] = "4";
$settings['theme_path'] = "default";
$settings['show_device'] = "0";
$settings['time_format'] = "h:i:s";
$settings['date_format'] = "d-m-Y";
$settings['panel_url'] = "if you are using webmin enter the url to your control panel"; // ?! What if webmin is not in use? Leave it blank?  : zer0
$settings['domain_size'] = "0.5"; // Not sure what this is  : zer0
$settings['cookie_url'] = "/misc.php?action=27015";
$settings['disable_plugin'] = "0"; // DEFAULT 0 : No ideer if this works. : zer0
$settings['new_posts'] = "5";
$settings['olark_key'] = ""; // TBD  : zer0
$settings['game_server'] = "enter the exact url to the remote files"; // If you are using a remote host enter the address here e.g http://yourdomain.com/remote 
?>
